services:
  app:
    build: .
    ports:
      - "8090:8080"

  postgres:
    image: postgres:latest
    environment:
      username: root
      password: root
      DB: studentsDkr07042026
    ports:
      - "5433:5432"