spring.application.name=docker-containerization

# Database connection
spring.datasource.url=jdbc:postgresql://postgres:5432/studentsDkr07042026
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create

# Show SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
